### PR TITLE
Changing the nest table format

### PR DESCRIPTION
**Pull request by ccev**
My nestscript fork will require a different table structure. this PR adds an update sql file.

It's only removing the `nest_submitted_by` columns which is neither being used by PMSF nor by madaos script. So it should be compatible

### CODE REVIEW

**Comment by whitewillem** [comment]
PMSF does insert into this column tho, but it looks like we never use the datal.
https://github.com/pmsf/PMSF/blob/master/lib/submit/Manual.php#L62
https://github.com/pmsf/PMSF/blob/master/lib/submit/Manual.php#L85

**Comment by ccev** [comment]
> PMSF does insert into this column tho, but it looks like we never use the data.
> https://github.com/pmsf/PMSF/blob/master/lib/submit/Manual.php#L62
> https://github.com/pmsf/PMSF/blob/master/lib/submit/Manual.php#L85

True, did not catch that. Either I let the column stay or you remove those references from the code. you decide

**Comment by nileplumb** [comment]
I'd say keep author, I believe some projects have used it such as WDR (not that i think nest querying via WDR is a much used feature, but it is still a feature)

**Comment by whitewillem** [comment]
Up to @jepke then. I dont care

**Comment by whitewillem** [comment]
Ok. Ill try to make use of the new polygon columns soon and merge this.

**Comment by ccev** [comment]
> Ok. Ill try to make use of the new polygon columns soon and merge this.

For refernce, `polygon_path` is saved exactly like the `coordinates` field in a geojson. just make sure to also support multipolygons (polygon_type = 1)

**Comment by whitewillem** [comment]
How does your version work tho? Can i just draw the polygon of each record we query?

**Comment by jepke** [comment]
@ccev  `nest_submitted_by` is still actively being used. Most nesting tools utilize the PMSF table would be nice if they fill that column so users can see the difference between user and bot submitted nests.

**Pull request merged**
