### PR TITLE
Fixed map load race condition affecting Safari browsers.

### PR DESCRIPTION
**Pull request by hokiepokedad2**
For Safari users, there was a race condition preventing the map from fully loading, especially the sidebar. The results of this were the side menu tabs appearing as links instead of intended tabs. More importantly, settings were not being saved to the users' localStorage if a user were to attempt to change a setting when the race condition has hit the failed path.

Test:
Open the map using Safari, either on iOS or desktop. Keep notice of the side menu tabs. If they appear as links, you've hit the bug. If you keep refreshing, you'll see that it'll eventually render as tabs.

### CODE REVIEW

**Comment by kbtbc** [comment]
This works to solve the issue I was having. 

Those who were having trouble saving quest filters are now happy.

**Comment by hokiepokedad2** [comment]
#189

**Comment by hokiepokedad2** [comment]
Fixes #189

**Comment by mattlesnake** [comment]
This fixed my issues too with the buttons appearing as links. Super
Good work figuring out the race condition.

**Pull request merged**
