### PR TITLE
New grunts

### PR DESCRIPTION
**Pull request by ccev**
This file has been created automatically. Please double-check before merging. 

From my tests/checks I've found it to be working

### CODE REVIEW

**Comment by nileplumb** [comment]
Can rockets 4 and 5 be named "Tier II" in your conversion scripts going forward?

**Comment by ccev** [comment]
Sure, why though?

**Comment by nileplumb** [comment]
> 
> 
> Sure, why though?

I think other projects refer to them as Tier II because they're the most difficult ones usually, they might be TIer II in the game code too can't recall

**Comment by clburlison** [comment]
It's WDR that decided to use "Tier II".
PoracleJS decided to go with "mixed".
Game data has null/no value which is why it's using empty string in PMSF. 

IMO PMSF should leave it as "" and if alternative projects want to implement additional logic that's on them to make changes.

**Comment by clburlison** [comment]
Also this PR has a ton of changes for a single file update....

**Comment by ccev** [comment]
> Also this PR has a ton of changes for a single file update....

that's because I changed the indent to 4 instead of 2 I guess

**Comment by muckelba** [comment]
> > Also this PR has a ton of changes for a single file update....
> 
> that's because I changed the indent to 4 instead of 2 I guess

No, the PR is just based on the master branch and is supposed to be merged into develop

**Comment by ccev** [comment]
> > > Also this PR has a ton of changes for a single file update....
> > 
> > 
> > that's because I changed the indent to 4 instead of 2 I guess
> 
> No, the PR is just based on the master branch and is supposed to be merged into develop

image
👀

**Pull request closed without merging**
