### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by MrRaichuGF**
Added 1411 & 1412 - easier difference by mit/ohne  | for the ones who can't read right 
Added 1504 & 1505 -  was missing
Editet 1508 & 1509 -  added Spacebar - was not matching 
Added 1912
Editet 1914 - for a better understanding of the switches 
Added 1915 - for a better understanding of the switches

### CODE REVIEW

**Review by gopeine — APPROVED** [review]
looks good

**Comment by TiMXL73** [comment]
- Must match full string from `items.json`
  - Greatball/Ultraball is a good fix.
  - "Golden Razz" is not. Use full string from items json.

- First letters should be capitalized.

- Some of the new entries are duplicates of old ones = bad
  - With AR-Scan Task x3
  - Without AR-Scan Task x2
  - Event Pokéstops only x2
  - Others?

About the «With/Without» string, you use "stack" instead of "inventory" («Stapel» vs «Inventar»). What is the commonly used official term? Keep the more relevant one while cleaning up.

**Review by MrRaichuGF — COMMENTED** [review]
Numbers changed a bit now ^^

Here we go again :)
First I'm sorry, could bet i doublechecked..

1502 "Golden Razz Berry" corrected
1505/1503 "Poffin" is fine?
1914/1911 "Quest Pokéstops only" fine?
I deleted my entrys and edited existing in
1929 I choosed Stack/Stapel, u would use Inventory/Inventar more for for itembag
1930

And again about 1929,1930 plus 1938
the translations seems not working, can't figure out why- maybe U know?

Greets and thank U !

**Comment by MrRaichuGF** [comment]
Different instances.. different versions 🙄excuse me.
Last three working

**Pull request merged**
